### ISSUE TITLE
Venmo Phone Number Verification

### ISSUE THREAD

**Issue by zachjharris** [vsalvino/clevelandtips#2]
If you don’t have any mutual friends (not sure what it’s called in Venmo) with someone, the app requires you to verify the last 4 digits of their phone number before you can send them any money.

**Comment by vsalvino** [comment]
Ah, I did not know that. I guess we will need have servers provide the last 4 of their phone number and add that to the site.

**Comment by zachjharris** [comment]
Can phone number be added as col #7 to the sheet?

**Comment by vsalvino** [comment]
It can be added as col 6, and we can bump cashapp up to 7.

**Comment by vsalvino** [comment]
@zachjharris FYI - we are going to do another data update at the end of the day, because submissions are flooding in like crazy right now. So if you don't manage to get a PR in by then, I will update the import.py script to push cashapp up to column 7 so we can continue with the import.

**Comment by vsalvino** [comment]
Merged via #5
