### ISSUE TITLE
Nothing populating in fields: SyntaxError: Unexpected token { in JSON at position 47102

### ISSUE THREAD

**Issue by jSadoski** [vsalvino/clevelandtips#6]
While loading the page, nothing gets populated.

This error is uncaught:
`SyntaxError: Unexpected token { in JSON at position 47102`

I'm thinking it's possible there's an unescaped character?

[Here's the current JSON file from my locals.](https://gist.github.com/jSadoski/9fcc9ddd1fd44b3a4a5f7db723314323)

**Comment by vsalvino** [comment]
Result of a bad data update. I reverted the broken change and moved it to a branch for review: https://github.com/vsalvino/clevelandtips/tree/broken
